services:
  mongodb:
    image: mongo:8.0
    container_name: muchtodo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: much_todo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - muchtodo-network

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: muchtodo-app:latest
    container_name: muchtodo-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env:ro
    environment:
      PORT: "8080"
      MONGO_URI: "mongodb://root:example@mongodb:27017/much_todo_db?authSource=admin"
      DB_NAME: "much_todo_db"
      JWT_SECRET_KEY: "assessment-secret-key"
      JWT_EXPIRATION_HOURS: "72"
      ENABLE_CACHE: "false"
      LOG_LEVEL: "DEBUG"
      LOG_FORMAT: "json"
    networks:
      - muchtodo-network

volumes:
  mongo_data:

networks:
  muchtodo-network:
    driver: bridge